// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5R7D0fOw2cd250XVuTnijvqnycMIbUj4',
    appId: '1:975182614277:web:8f556a4eb9eba272a4716c',
    messagingSenderId: '975182614277',
    projectId: 'yapeclon-23dd2',
    authDomain: 'yapeclon-23dd2.firebaseapp.com',
    storageBucket: 'yapeclon-23dd2.firebasestorage.app',
    measurementId: 'G-43QHL4NBFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0ThYcpTr8qvv3gHPb3xGNy4CvgWckDw',
    appId: '1:975182614277:android:2b6c743cbc48c52aa4716c',
    messagingSenderId: '975182614277',
    projectId: 'yapeclon-23dd2',
    storageBucket: 'yapeclon-23dd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl8PAAswz-phYi7m3XXfnU0Nr5bHd8328',
    appId: '1:975182614277:ios:0835cf428ee7ad86a4716c',
    messagingSenderId: '975182614277',
    projectId: 'yapeclon-23dd2',
    storageBucket: 'yapeclon-23dd2.firebasestorage.app',
    iosBundleId: 'com.example.yapeclon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl8PAAswz-phYi7m3XXfnU0Nr5bHd8328',
    appId: '1:975182614277:ios:0835cf428ee7ad86a4716c',
    messagingSenderId: '975182614277',
    projectId: 'yapeclon-23dd2',
    storageBucket: 'yapeclon-23dd2.firebasestorage.app',
    iosBundleId: 'com.example.yapeclon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5R7D0fOw2cd250XVuTnijvqnycMIbUj4',
    appId: '1:975182614277:web:78b8e926d08abd6da4716c',
    messagingSenderId: '975182614277',
    projectId: 'yapeclon-23dd2',
    authDomain: 'yapeclon-23dd2.firebaseapp.com',
    storageBucket: 'yapeclon-23dd2.firebasestorage.app',
    measurementId: 'G-PFYP3X76X4',
  );
}
